// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPtFZNLynoHXVniNEvrl9GO1y4rA21dFw',
    appId: '1:264763697454:web:6bccdc3a42cde1e8ba72bf',
    messagingSenderId: '264763697454',
    projectId: 'luis-honorato-auth-app',
    authDomain: 'luis-honorato-auth-app.firebaseapp.com',
    storageBucket: 'luis-honorato-auth-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqg37cEdIAW7k6LiMaq_q7TVwgY-6YMU4',
    appId: '1:264763697454:android:72d63d4a0f74ca42ba72bf',
    messagingSenderId: '264763697454',
    projectId: 'luis-honorato-auth-app',
    storageBucket: 'luis-honorato-auth-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbiV23nsn7kaXsWt_mROw4utGol4SBq4',
    appId: '1:264763697454:ios:02a9a7b55694e3eeba72bf',
    messagingSenderId: '264763697454',
    projectId: 'luis-honorato-auth-app',
    storageBucket: 'luis-honorato-auth-app.appspot.com',
    iosClientId: '264763697454-ipo06n1479jbr9tiavi94viv9kgck19s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEbiV23nsn7kaXsWt_mROw4utGol4SBq4',
    appId: '1:264763697454:ios:02a9a7b55694e3eeba72bf',
    messagingSenderId: '264763697454',
    projectId: 'luis-honorato-auth-app',
    storageBucket: 'luis-honorato-auth-app.appspot.com',
    iosClientId: '264763697454-ipo06n1479jbr9tiavi94viv9kgck19s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
